services:
  llama_mariadb:
    image: mariadb:11.6.2
    container_name: llama_mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_CONFIG_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"


